name: Version & Changelog

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          manifest-file: .release-please-manifest.json
